function entries = changelog(show_output)
% CHANGELOG Project change log for V46 MCMF integration.
% Usage:
%   entries = changelog();
%   entries = changelog(true);   % print to console
%
% This file is intended for report writing and progress tracking.

if nargin < 1
    show_output = true;
end

entries = struct( ...
    'date', {}, ...
    'step', {}, ...
    'title', {}, ...
    'files', {}, ...
    'summary', {}, ...
    'validation', {} ...
    );

entries(end+1) = makeEntry( ...
    '2026-04-01', ...
    'Step 1', ...
    'Add MCMF switch flag', ...
    {'example_V46_mcmf_proposal.m'}, ...
    ['Added USE_MCMF_ASSIGNMENT flag to V46 so legacy and future MCMF paths can be toggled. ' ...
     'Current execution still uses legacy selection logic.'], ...
    'No behavior path change introduced by this flag alone.' ...
    );

entries(end+1) = makeEntry( ...
    '2026-04-01', ...
    'Step 2', ...
    'Refactor bidding and selection into helper functions', ...
    {'example_V46_mcmf_proposal.m'}, ...
    ['Refactored PENDING_BIDDING and PENDING_SELECTION logic into helper functions: ' ...
     'buildInterceptorBidsForTarget(...) and runLegacyInterceptorSelection(...). ' ...
     'Algorithm and branch behavior were intentionally preserved.'], ...
    ['Self-check completed by comparing V45 and V46 outputs: log content matched ' ...
     '(ignoring timestamp header) and MAT field-level equality check passed.'] ...
    );

entries(end+1) = makeEntry( ...
    '2026-04-01', ...
    'Step 3', ...
    'Build global allocation input model for MCMF', ...
    {'example_V46_mcmf_proposal.m'}, ...
    ['Added MCMF_SLOTS_PER_TARGET and new helper buildGlobalAllocationInputs(...). ' ...
     'The helper builds calling target set, candidate sensors, slot expansion, ' ...
     'sensor-target cost matrix, and sensor-slot cost matrix. ' ...
     'Input construction is now called in PENDING_SELECTION before legacy assignment.'], ...
    ['Execution check passed on V46 simulation. ' ...
     'Selection still handled by legacy path, so intended behavior is unchanged.'] ...
    );

entries(end+1) = makeEntry( ...
    '2026-04-02', ...
    'Step 4', ...
    'Integrate MCMF solver into PENDING_SELECTION', ...
    {'example_V46_mcmf_proposal.m'}, ...
    ['Implemented solveInterceptorAssignmentMCMF(...) and runMCMFInterceptorSelection(...). ' ...
     'When USE_MCMF_ASSIGNMENT=true, PENDING_SELECTION now builds global inputs and ' ...
     'runs one global assignment over expanded target slots instead of legacy minimax/greedy selection.'], ...
    ['Root V46 execution completed successfully and generated output files. ' ...
     'Run log contains [MCMF] entries with assigned slots and total cost per event.'] ...
    );

if show_output
    fprintf('\n=== MIE8888 V46 Change Log ===\n');
    for i = 1:numel(entries)
        fprintf('\n[%s] %s - %s\n', entries(i).date, entries(i).step, entries(i).title);
        fprintf('Files: %s\n', strjoin(entries(i).files, ', '));
        fprintf('Summary: %s\n', entries(i).summary);
        fprintf('Validation: %s\n', entries(i).validation);
    end
    fprintf('\n');
end
end

function e = makeEntry(date, step, title, files, summary, validation)
e = struct( ...
    'date', date, ...
    'step', step, ...
    'title', title, ...
    'files', {files}, ...
    'summary', summary, ...
    'validation', validation ...
    );
end
